name: CI
on:
  - push
  - pull_request
jobs:
  test:
    name: Julia ${{ matrix.version }} - ${{ matrix.os }} - ${{ matrix.arch }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        #TODO version: ["1.0", "1.4", "1.5", "nightly"]
        #TODO os: [ubuntu-latest, windows-latest, macOS-latest]
        version: ["1.4"]
        os: [ubuntu-latest]
        # <<#HAS_EXCLUDES>>
        # exclude:
        # <</HAS_EXCLUDES>>
        # <<#EXCLUDES>>
        #   - os: <<&E_OS>>
        #     arch: <<&E_ARCH>>
        #     <<#E_VERSION>>
        #     version: '<<&E_VERSION>>'
        #     <</E_VERSION>>
        # <</EXCLUDES>>
    steps:
      - uses: actions/checkout@v2
      - uses: julia-actions/setup-julia@v1
        with:
          version: ${{ matrix.version }}
          # arch: ${{ matrix.arch }}
      - uses: julia-actions/julia-buildpkg@latest
      - uses: julia-actions/julia-runtest@latest
