name: CI
on:
  - push
  - pull_request
jobs:
  test:
    name: Julia ${{ matrix.version }} - ${{ matrix.os }} - ${{ matrix.arch }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]
        # version: ["1.0", "1.4", "1.5", "nightly"]
        # 1.0: package does not work
        # 1.4: package works
        # 1.5: not yet supported by Actions
        # nightly: package works
        version: ["1.4", "nightly"]
        # arch: [x64, x86]
        arch: [x64]
        # <<#HAS_EXCLUDES>>
        # exclude:
        # <</HAS_EXCLUDES>>
        # <<#EXCLUDES>>
        #   - os: <<&E_OS>>
        #     arch: <<&E_ARCH>>
        #     <<#E_VERSION>>
        #     version: '<<&E_VERSION>>'
        #     <</E_VERSION>>
        # <</EXCLUDES>>
        # include:
    steps:
      - uses: actions/checkout@v2
      - uses: julia-actions/setup-julia@v1
        with:
          version: ${{ matrix.version }}
          arch: ${{ matrix.arch }}
      - uses: julia-actions/julia-buildpkg@latest
      - uses: julia-actions/julia-runtest@latest
